# Generated by Django 6.0 on 2025-12-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_category', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('licence_id', models.AutoField(primary_key=True, serialize=False)),
                ('licence_name', models.CharField(max_length=45)),
                ('licence_description', models.CharField(max_length=255)),
                ('licence_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'db_table': 'licence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=60)),
                ('product_description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('dues', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('image_front', models.CharField(max_length=200)),
                ('image_back', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
